import { ADLaM_Display } from 'next/font/google'
import './globals.css'

const geistSans = ADLaM_Display({ subsets: ['latin'], weight: '400' })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={geistSans.className}>{children}</body>
        </html>
    )
}
